1. The Blunder
    SELECT CEIL(AVG(Salary)-AVG(REPLACE(Salary,'0','')))
    FROM EMPLOYEES;

2. Top Earners
    SELECT MAX(SALARY*MONTHS), COUNT(*) FROM EMPLOYEE
    WHERE (SALARY*MONTHS) = (SELECT MAX(SALARY*MONTHS)
    FROM EMPLOYEE);

3. Weather Observation Station 2
    SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2)
    FROM STATION;